version: 2
jobs:
  build:
    working_directory: ~/prisoner-trianing-app
    docker:
    - image: cimg/ruby:2.7.5-node
      environment:
        BUNDLER_VERSION: 2.1.4
        RAILS_ENV: test
    - image: cimg/mysql:8.0
    steps:
    - checkout
    - restore_cache:
        keys:
        - gem-cache-v1-{{ checksum "~/prisoner-training-app/Gemfile.lock" }}
        - gem-cache-v1-
    - run:
        command: bundle install --path=vendor/bundle --jobs=4 --retry=3
    - save_cache:
        key: gem-cache-v1-{{ checksum "~/prisoner-training-app/Gemfile.lock" }}
        paths:
        - ~/prisoner-training-app/vendor/bundle
    - run:
        command: mv ~/prisoner-training-app/config/database.yml.ci ~/prisoner-training-app/config/database.yml
    - run:
        command: bundle exec rails db:create
    - run:
        command: bundle exec rails db:migrate
    - run:
        command: bundle exec rspec
workflows:
  version: 2
  build_and_test:
    jobs:
    - build

# Original config.yml file:
# version: 2.1
# 
# jobs:
#   build:
#     working_directory: ~/prisoner-trianing-app
#     docker:
#       - image: cimg/ruby:2.7.5-node
#         environment:
#           BUNDLER_VERSION: 2.1.4
#           RAILS_ENV: 'test'
#       - image: cimg/mysql:8.0
#     steps:
#       - checkout
# 
#       - restore_cache:
#           keys:
#             - gem-cache-v1-{{ checksum \"~/prisoner-training-app/Gemfile.lock\" }}
#             - gem-cache-v1-
#       - run: bundle install --path=vendor/bundle --jobs=4 --retry=3
#       - save_cache:
#           key: gem-cache-v1-{{ checksum \"~/prisoner-training-app/Gemfile.lock\" }}
#           paths:
#             - ~/prisoner-training-app/vendor/bundle
# 
#       - run: mv ~/prisoner-training-app/config/database.yml.ci ~/prisoner-training-app/config/database.yml
# 
#       - run: bundle exec rails db:create
#       - run: bundle exec rails db:migrate
#       - run: bundle exec rspec
# 
# 
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build