version: 2.1

jobs:
  test_backend:
    working_directory: ~/api
    docker:
      - image: cimg/ruby:2.7.5-node
        environment:
          BUNDLER_VERSION: 2.1.4
          RAILS_ENV: 'test'
      - image: cimg/mysql:8.0
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ROOT_PASSWORD: password
    steps:
      - checkout

      - restore_cache:
          keys:
            - gem-cache-v1-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-
      - run: bundle install --path=vendor/bundle --jobs=4 --retry=3
      - save_cache:
          key: gem-cache-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/api/vendor/bundle

      - run: bundle exec rubocop --fail-level W --display-only-fail-level-offenses

      - run: mv config/database.yml.ci config/database.yml

      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate
      - run: bundle exec rspec

  test_frontend:
    working_directory: ~/web
    docker:
      - image: cimg/node:14.4.0
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./frontend/package-lock.json" }}
            - v1-dependencies-
      - run: npm --prefix ./frontend install ./frontend
      - save_cache:
          key: v1-dependencies-{{ checksum "./frontend/package-lock.json" }}
          paths:
            - ~/web/frontend/node_modules
      - run:
          name: run eslint
          command: |
            cd frontend
            npm run lint
      - run:
          name: run prettier check
          command: |
            cd frontend
            npm run format
      - run:
          name: run prettier fix
          command: |
            cd frontend
            npm run format:fix
      - run:
          name: run test
          command: |
            cd frontend
            npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test_backend
      - test_frontend
