name: "Build and Test"
on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: mysql:8.0
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: password
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.5'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install --path=vendor/bundle --jobs=4 --retry=3
      # このrubocopを行う前にbundle installが必要かな
      - name: Run rubocop
        run: bundle exec rubocop --fail-level W --display-only-fail-level-offenses
